### DISCUSSION TITLE
Cant set monitor resolution

### DISCUSSION THREAD

**Discussion by Felipe-9** [hyprwm/Hyprland#10080] [Bugs - Config]
I set my monitor resolution to its highres but it doesnt apply.

`hyprctl monitors all`:
```
Monitor HDMI-A-1 (ID 0):
               1920x1080@60.00000 at 0x0
               description: OEM 22W_LCD_TV
               make: OEM
               model: 22W_LCD_TV
               serial: 
               active workspace: 1 (1)
               special workspace: 0 ()
               reserved: 0 0 0 0
               scale: 1.50
               transform: 0
               focused: yes
               dpmsStatus: 1
               vrr: false
               solitary: 0
               activelyTearing: false
               directScanoutTo: 0
               disabled: false
               currentFormat: XRGB8888
               mirrorOf: none
               availableModes: 1920x1080@60.00Hz 1920x1080@59.94Hz 1920x1080@50.00Hz 1920x1080@24.00Hz 1920x10>
Hz 1280x1024@75.03Hz 1152x864@75.00Hz 1280x720@60.00Hz 1280x720@60.00Hz 1280x720@59.94Hz ...
```
config regarding monitor:
```
monitor=, preferred, auto, 1.50
monitor=HDMI-A-1, 1920x1080@60, auto, 1.50
```

I can see the resolution is wrong on every game i try to open and as well as the following command

`swww query`
```
HDMI-A-1: 1280x720, scale: 1.5, currently displaying: image: /path/wallpaper.gif
```
