### DISCUSSION TITLE
A black box window appears after starting VirtualBox or guest OS

### DISCUSSION THREAD

**Discussion by c02y** [hyprwm/Hyprland#10877] [Q&A]
Whenever I start VirtualBox or VirtualBox Guest OS, a black box window appears for a few seconds.

The VirtualBox program or guest OS, after that, is working fine, but the black box window is quite annoying.

Is there any chance I can fix this? Not sure if this is the problem of VirtualBox or Wayland or Hyprland. (No such issue on X11)

FYI:
virtualbox 7.1.10-1
hyprland 0.49.0-2
wayland 1.23.1-2

Screenshot:
![Recording 2025-06-28 at 15 29 18](https://github.com/user-attachments/assets/ec8d0a6e-6d1d-4c4f-ad9e-bb016921ed51)

**Comment by vaxerski** [comment]
I'd guess it's virtualbox opening a weird window

**Reply by c02y** [reply]
The following text is from `hyprctl clients`, the first one is the black box window, the second one is the real VirtualBox manager window. 

The main difference is the `class/title/initialClass/initialTitle`. And they are all under xwayland.

```
Window 5645c3ac3050 -> VirtualBox:
    mapped: 1
    hidden: 0
    at: 1279,719
    size: 800,800
    workspace: 1 (1)
    floating: 1
    pseudo: 0
    monitor: 0
    class: VirtualBox
    title: VirtualBox
    initialClass: VirtualBox
    initialTitle: VirtualBox
    pid: 159348
    xwayland: 1
    pinned: 0
    fullscreen: 0
    fullscreenClient: 0
    grouped: 0
    tags:
    swallowing: 0
    focusHistoryID: 1
    inhibitingIdle: 0
    xdgTag:
    xdgDescription:

Window 5645c42749a0 -> Oracle VirtualBox Manager:
    mapped: 1
    hidden: 0
    at: 0,30
    size: 2560,1410
    workspace: 4 (4)
    floating: 0
    pseudo: 0
    monitor: 0
    class: VirtualBox Manager
    title: Oracle VirtualBox Manager
    initialClass: VirtualBox Manager
    initialTitle: Oracle VirtualBox Manager
    pid: 159348
    xwayland: 1
    pinned: 0
    fullscreen: 0
    fullscreenClient: 0
    grouped: 0
    tags:
    swallowing: 0
    focusHistoryID: 0
    inhibitingIdle: 0
    xdgTag:
    xdgDescription:

```
