### DISCUSSION TITLE
Wayland compositor hyprland won’t start

### DISCUSSION THREAD

**Discussion by enoren5** [hyprwm/Hyprland#3995] [Q&A] [answered]
I decided to experiment with Hyprland. On Manjaro I installed it with `yay`, made sure all my other system components were up to date, and rebooted. When I select Hyprland from ldm, after entering my password and press enter, I get a black screen with a white cursor in the top left. After about 10 seconds, ldm re-appears. 

(It's worth mentioning that `swayfx` has the exact same issue. Although I am able to log into Wayland-based compositor Gnome / mutter as I write this discussion thread on GitHub. )

Before I log an Issue as a bug, I figure I should ask here in case I am  missing something trivial like a dependency or did something wrong with my installation.

When I search Google for '*manjaro wayland won't start*' (with variations), a lot of Wayland KDE Plasma issues turn up. Seems Plasma is more popular with Manjaro users.

What other information could I provide to help troubleshoot?

Here is: `$ inxi -Fazy` : https://pastebin.com/j7esTcu9

And here is: `$ inxi -GSa` 

```
System:
  Host: <hostname> Kernel: 6.6.1-1-MANJARO arch: x86_64 bits: 64 compiler: gcc
    v: 13.2.1 clocksource: tsc available: acpi_pm
    parameters: BOOT_IMAGE=/boot/vmlinuz-6.6-x86_64
    root=UUID=d8f51c21-a5ce-4611-973c-b7d694ae22a1 rw apparmor=1
    security=apparmor resume=UUID=6a544b3a-7b7d-4fc0-b121-0f55042fc081
    udev.log_priority=3 video=vesafb:mode=3840x1600-32,mtrr:3,ywrap
  Desktop: GNOME v: 45.1 tk: GTK v: 3.24.38 wm: gnome-shell dm: LightDM
    v: 1.32.0 Distro: Manjaro Linux base: Arch Linux
Graphics:
  Device-1: AMD Navi 23 [Radeon RX 6600/6600 XT/6600M] vendor: Sapphire
    driver: amdgpu v: kernel arch: RDNA-2 code: Navi-2x process: TSMC n7 (7nm)
    built: 2020-22 pcie: gen: 4 speed: 16 GT/s lanes: 16 ports: active: DP-3
    empty: DP-1,DP-2,HDMI-A-1 bus-ID: 03:00.0 chip-ID: 1002:73ff
    class-ID: 0300
  Device-2: Logitech C922 Pro Stream Webcam driver: snd-usb-audio,uvcvideo
    type: USB rev: 2.0 speed: 480 Mb/s lanes: 1 mode: 2.0 bus-ID: 1-13:12
    chip-ID: 046d:085c class-ID: 0102 serial: EB8FAF8F
  Display: wayland server: X.org v: 1.21.1.9 with: Xwayland v: 23.2.2
    compositor: gnome-shell driver: X: loaded: amdgpu
    unloaded: modesetting,radeon alternate: fbdev,vesa dri: radeonsi
    gpu: amdgpu display-ID: 0
  Monitor-1: DP-3 model: LG (GoldStar) HDR WQHD serial: 520115 built: 2018
    res: 3840x1600 dpi: 111 gamma: 1.2 size: 879x366mm (34.61x14.41")
    diag: 952mm (37.5") modes: max: 3840x1600 min: 640x480
  API: EGL v: 1.5 hw: drv: amd radeonsi platforms: device: 0 drv: radeonsi
    device: 1 drv: swrast surfaceless: drv: radeonsi wayland: drv: radeonsi x11:
    drv: radeonsi inactive: gbm
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 23.1.9-manjaro1.1
    glx-v: 1.4 direct-render: yes renderer: AMD Radeon RX 6600 XT (navi23 LLVM
    16.0.6 DRM 3.54 6.6.1-1-MANJARO) device-ID: 1002:73ff memory: 7.81 GiB
    unified: no display-ID: :0.0
```
