### DISCUSSION TITLE
How do I increase the size of the Hyprland's Waybar?

### DISCUSSION THREAD

**Discussion by Dolbaeb777K** [hyprwm/Hyprland#4712] [Q&A] [answered]
Adding to **[TOP & BOT] " SummitSplit "font-size": 18px,** " - Nothing changes after restarting Waybar via **super+alt+b**. Hyperland's waybar seems too small to me and I want to enlarge it. 
How can I do it?

**Comment by fufexan** [comment, marked as answer]
First of all, this is a Waybar question, not Hyprland, so it does not belong here.
Second of all, all you have to do is add this or whatever value you prefer in your waybar's `style.css`:
```css
window#waybar {
  min-height: 18px; /* set waybar's height to 18px */
  font-size: 18px; /* set only the font size to be bigger, which in turn will adjust the height of other elements */
}
```
