### DISCUSSION TITLE
visually mark app/ special title, if in fullscreen

### DISCUSSION THREAD

**Discussion by aloispichler** [hyprwm/Hyprland#7637] [Q&A]
is there a way to have a special title, a tag or something visible (a red border or so, with winodowrule), if the app runs in fullscreen (as with `fullscreen, 1`)? Any ideas? – Thanks!

**Comment by vaxerski** [comment]
fullscreen 1 is maximize.

Title no, but you can change for example the border color:
```
windowrulev2=bordercolor rgba(ff55ffee), fullscreen:1
```

**Reply by aloispichler** [reply]
Yes, that _would_ work, too bad I have `no_gaps_when_only= 1`.

**Comment by MahouShoujoMivutilde** [comment]
If you use waybar, there is `window#waybar.fullscreen` ([docs](https://github.com/Alexays/Waybar/wiki/Module:-Hyprland#window)), which is active when the current workspace has fullscreen window.

It can be applied to the whole bar or a specific part of it.

E.g.

```css
window#waybar.fullscreen #workspaces button.active {
  background: rgba(244, 190, 204, 0.85);
  color: rgba(27, 27, 27, 1.0);
}
```

![waybar](https://github.com/user-attachments/assets/8cc56d92-b92b-4676-aee0-364707419763)


(idk how to make it reflect the state of windows on all the workspaces) 

And if you don't - `hyprctl activewindow -j | jq '.fullscreen'` is your friend.
