### DISCUSSION TITLE
Cannot find all available monitor modes in `hyprctl  monitors all`

### DISCUSSION THREAD

**Discussion by Ziqi-Yang** [hyprwm/Hyprland#9423] [Q&A] [answered]
<details>
<summary>The result of `hyprctl monitors all`:</summary>

```
❯ hyprctl monitors all
Monitor eDP-1 (ID 0):
        3072x1920@120.00200 at 0x0
        description: Lenovo Group Limited 0x8AB1
        make: Lenovo Group Limited
        model: 0x8AB1
        serial:
        active workspace: 8 (8)
        special workspace: 0 ()
        reserved: 0 35 0 0
        scale: 1.20
        transform: 0
        focused: no
        dpmsStatus: 1
        vrr: false
        solitary: 0
        activelyTearing: false
        directScanoutTo: 0
        disabled: false
        currentFormat: XRGB8888
        mirrorOf: none
        availableModes: 3072x1920@60.00Hz 3072x1920@120.00Hz

Monitor HDMI-A-1 (ID 1):
        3840x2160@60.00000 at -2560x0
        description: AOC Q27G2S 18DQ8HA023604
        make: AOC
        model: Q27G2S
        serial: 18DQ8HA023604
        active workspace: 1 (terminal)
        special workspace: 0 ()
        reserved: 0 35 0 0
        scale: 1.50
        transform: 0
        focused: yes
        dpmsStatus: 1
        vrr: false
        solitary: 0
        activelyTearing: false
        directScanoutTo: 0
        disabled: false
        currentFormat: XRGB8888
        mirrorOf: none
        availableModes: 3840x2160@60.00Hz 3840x2160@59.94Hz 3840x2160@50.00Hz 1920x1080@120.00Hz 1920x1080@119.88Hz 1920x1080@60.00Hz 1920x1080@60.00Hz 1920x1080@59.94Hz 1920x1080@50.00Hz 1280x1024@75.03Hz 1280x1024@60.02Hz 1280x720@60.00Hz 1280x720@59.94Hz 1280x720@50.00Hz 1024x768@119.99Hz 1024x768@75.03Hz 1024x768@70.07Hz 1024x768@60.00Hz 832x624@74.55Hz 800x600@75.00Hz 800x600@72.19Hz 800x600@60.32Hz 800x600@56.25Hz 720x576@50.00Hz 720x576@50.00Hz 720x480@60.00Hz 720x480@60.00Hz 720x480@59.94Hz 720x480@59.94Hz 640x480@75.00Hz 640x480@72.81Hz 640x480@66.67Hz 640x480@60.00Hz 720x400@70.08Hz
```

</details>

<details>
<summary>The result of `wlr-rander`:</summary>

```
❯ wlr-randr
eDP-1 "Lenovo Group Limited 0x8AB1  (eDP-1)"
  Make: Lenovo Group Limited
  Model: 0x8AB1
  Serial: (null)
  Physical size: 310x200 mm
  Enabled: yes
  Modes:
    3072x1920 px, 60.000000 Hz (preferred)
    3072x1920 px, 120.001999 Hz (current)
  Position: 0,0
  Transform: normal
  Scale: 1.199219
  Adaptive Sync: disabled
HDMI-A-1 "AOC Q27G2S 18DQ8HA023604 (HDMI-A-1)"
  Make: AOC
  Model: Q27G2S
  Serial: 18DQ8HA023604
  Physical size: 600x340 mm
  Enabled: yes
  Modes:
    3840x2160 px, 60.000000 Hz (current)
    3840x2160 px, 59.939999 Hz
    3840x2160 px, 50.000000 Hz
    1920x1080 px, 120.000000 Hz
    1920x1080 px, 119.879997 Hz
    1920x1080 px, 60.000000 Hz
    1920x1080 px, 60.000000 Hz
    1920x1080 px, 59.939999 Hz
    1920x1080 px, 50.000000 Hz
    1280x1024 px, 75.025002 Hz
    1280x1024 px, 60.020000 Hz
    1280x720 px, 60.000000 Hz
    1280x720 px, 59.939999 Hz
    1280x720 px, 50.000000 Hz
    1024x768 px, 119.988998 Hz
    1024x768 px, 75.028999 Hz
    1024x768 px, 70.069000 Hz
    1024x768 px, 60.004002 Hz
    832x624 px, 74.551003 Hz
    800x600 px, 75.000000 Hz
    800x600 px, 72.188004 Hz
    800x600 px, 60.317001 Hz
    800x600 px, 56.250000 Hz
    720x576 px, 50.000000 Hz
    720x576 px, 50.000000 Hz
    720x480 px, 60.000000 Hz
    720x480 px, 60.000000 Hz
    720x480 px, 59.939999 Hz
    720x480 px, 59.939999 Hz
    640x480 px, 75.000000 Hz
    640x480 px, 72.808998 Hz
    640x480 px, 66.667000 Hz
    640x480 px, 60.000000 Hz
    720x400 px, 70.082001 Hz
  Position: -2560,0
  Transform: normal
  Scale: 1.500000
  Adaptive Sync: disabled
  ```

</details>

<details>
<summary>The result of `cat /sys/class/drm/card1-HDMI-A-1/modes`</summary>

```
❯ cat /sys/class/drm/card1-HDMI-A-1/modes
3840x2160
3840x2160
3840x2160
1920x1080
1920x1080
1920x1080
1920x1080
1920x1080
1920x1080
1280x1024
1280x1024
1280x720
1280x720
1280x720
1024x768
1024x768
1024x768
1024x768
832x624
800x600
800x600
800x600
800x600
720x576
720x576
720x480
720x480
720x480
720x480
640x480
640x480
640x480
640x480
720x400
```
</details>

  
  
  However, the HDMI-A-1 monitor is supposed to have `2560x1440@120` since I set it in my configuration and worked fine on my old computer. However, when I switched to my new computer and installed the latest hyprland-git, it cannot find this monitor mode. (I uses NixOS. However, I connected to that monitor after upgrading my nixos system, including hyprland)
  
  I also tried to find whether the monitor has 2560x1440@120 on Windows system on my new computer, and it shows that it does have this mode on Windows. 

  NOTE, I uses the same HDMI cable for those tests mentioned above.
