### DISCUSSION TITLE
External monitor lag when using hyprland on nvidia gpu

### DISCUSSION THREAD

**Discussion by mikorozek** [hyprwm/Hyprland#9688] [Q&A]
Hello, I have a problem. I am using Hyprland 0.47.2 with a nvidia driver 570.124.04. When using an external monitor the fps is starting ok and oscillates around 60, but after while it drops to 30 fps and doesn't increase anymore. This is happening only when I'm on a workspace on my external monitor. Yesterday it worked just fine with 60 fps, but suddenly when I turned on my laptop this morning it began to happen. 
```
mrozek@mrozek-lenovo-p53:~$ hyprctl monitors all
Monitor eDP-1 (ID 0):
        1920x1080@60.00800 at 1920x0
        description: Chimei Innolux Corporation 0x15E8
        make: Chimei Innolux Corporation
        model: 0x15E8
        serial:
        active workspace: 2 (2)
        special workspace: 0 ()
        reserved: 0 36 0 0
        scale: 1.00
        transform: 0
        focused: no
        dpmsStatus: 1
        vrr: false
        solitary: 0
        activelyTearing: false
        directScanoutTo: 0
        disabled: false
        currentFormat: XRGB8888
        mirrorOf: none
        availableModes: 1920x1080@60.01Hz

Monitor HDMI-A-1 (ID 1):
        1920x1080@60.00000 at 0x0
        description: Samsung Electric Company LS24DG30X H8CX502229
        make: Samsung Electric Company
        model: LS24DG30X
        serial: H8CX502229
        active workspace: 1 (1)
        special workspace: 0 ()
        reserved: 0 36 0 0
        scale: 1.00
        transform: 0
        focused: yes
        dpmsStatus: 1
        vrr: false
        solitary: 0
        activelyTearing: false
        directScanoutTo: 0
        disabled: false
        currentFormat: XRGB8888
        mirrorOf: none
        availableModes: 1920x1080@60.00Hz 1920x1080@59.94Hz 1920x1080@50.00Hz 1680x1050@59.95Hz 1600x900@60.00Hz 1280x1024@75.03Hz 1280x1024@60.02Hz 1440x900@59.89Hz 1280x800@59.81Hz 1152x864@75.00Hz 1280x720@60.00Hz 1280x720@59.94Hz 1280x720@50.00Hz 1024x768@75.03Hz 1024x768@70.07Hz 1024x768@60.00Hz 800x600@75.00Hz 800x600@72.19Hz 800x600@60.32Hz 800x600@56.25Hz 720x576@50.00Hz 720x480@59.94Hz 640x480@75.00Hz 640x480@72.81Hz 640x480@59.94Hz
```
Here is output of hyprctl monitors all and here is my config

```
# monitor=eDP-1,disable
monitor=HDMI-A-1,1920x1080@60,auto,1.0
monitor=eDP-1,1920x1080@60,auto,1.0


$terminal = kitty
$fileManager = nautilus
$menu = wofi --show drun

exec-once = waybar & swaync & hypridle & hyprpaper

#############################
### ENVIRONMENT VARIABLES ###
#############################


env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = BROWSER, brave



general {
    gaps_in = 5
    gaps_out = 20

    border_size = 2

    col.active_border = rgba(e47c84ee) rgba(e1999fee) 45deg
    col.inactive_border = rgba(595959aa)


    resize_on_border = false

    allow_tearing = false

    layout = dwindle
}


decoration {
    rounding = 10
    rounding_power = 2


    active_opacity = 1.0
    inactive_opacity = 1.0

    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }


    blur {
        enabled = true
        size = 3
        passes = 1

        vibrancy = 0.1696
    }
}


animations {
    enabled = yes, please :)



    bezier = easeOutQuint,0.23,1,0.32,1
    bezier = easeInOutCubic,0.65,0.05,0.36,1
    bezier = linear,0,0,1,1
    bezier = almostLinear,0.5,0.5,0.75,1.0
    bezier = quick,0.15,0,0.1,1

    animation = global, 1, 10, default
    animation = border, 1, 5.39, easeOutQuint
    animation = windows, 1, 4.79, easeOutQuint
    animation = windowsIn, 1, 4.1, easeOutQuint, popin 87%
    animation = windowsOut, 1, 1.49, linear, popin 87%
    animation = fadeIn, 1, 1.73, almostLinear
    animation = fadeOut, 1, 1.46, almostLinear
    animation = fade, 1, 3.03, quick
    animation = layers, 1, 3.81, easeOutQuint
    animation = layersIn, 1, 4, easeOutQuint, fade
    animation = layersOut, 1, 1.5, linear, fade
    animation = fadeLayersIn, 1, 1.79, almostLinear
    animation = fadeLayersOut, 1, 1.39, almostLinear
    animation = workspaces, 1, 1.94, almostLinear, fade
    animation = workspacesIn, 1, 1.21, almostLinear, fade
    animation = workspacesOut, 1, 1.94, almostLinear, fade
}

dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

master {
    new_status = master
}

cursor {
    no_hardware_cursors = true
}

misc {
    force_default_wallpaper = 1 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
}

input {
    kb_layout = pl
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
    follow_mouse = 0
    touchpad {
        natural_scroll = true
    }
}

gestures {
    workspace_swipe = false
}


device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

opengl {
    nvidia_anti_flicker = false
}

# See https://wiki.hyprland.org/Configuring/Keywords/
$mainMod = SUPER # Sets "Windows" key as main modifier

# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = $mainMod, T, exec, $terminal
bind = $mainMod, Q, killactive,
bind = $mainMod, M, fullscreen, 1
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, slash, exec, $menu
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, C, togglesplit, # dwindle

bind = , PRINT, exec, hyprshot -m window
bind = shift, PRINT, exec, hyprshot -m region
bind = $mainMod, PRINT, exec, hyprshot -m output

bind = $mainMod, h, movefocus, l
bind = $mainMod, l, movefocus, r
bind = $mainMod, k, movefocus, u
bind = $mainMod, j, movefocus, d
bind = $mainMod SHIFT, k, movewindow, u
bind = $mainMod SHIFT, j, movewindow, d
bind = $mainMod SHIFT, h, movewindow, l
bind = $mainMod SHIFT, l, movewindow, r

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Example special workspace (scratchpad)
bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Laptop multimedia keys for volume and LCD brightness
bind = ,XF86AudioRaiseVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ +5%
bind = ,XF86AudioLowerVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ -5%
bindel = ,XF86AudioMute, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, pactl set-source-mute @DEFAULT_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl s 10%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl s 10%-

# Requires playerctl
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous

windowrulev2 = suppressevent maximize, class:.*

windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
```
Do you see anything that could be causing this issue?

8947-8f4786397f3e)
