### ISSUE TITLE
Couldn't commit output on extended monitor

### ISSUE THREAD

**Issue by hydroakri** [hyprwm/Hyprland#1018]
the extended monitor not work in hyprland
My laptop:
```
System:
  Host: archlinux Kernel: 6.0.8-zen1-1-zen arch: x86_64 bits: 64
    Desktop: Hyprland Distro: Arch Linux
Graphics:
  Device-1: NVIDIA GA106M [GeForce RTX 3060 Mobile / Max-Q] driver: nvidia
    v: 520.56.06
  Device-2: AMD Cezanne [Radeon Vega Series / Radeon Mobile Series]
    driver: amdgpu v: kernel
  Device-3: Cheng Uei Precision Industry (Foxlink) HP Wide Vision HD Camera
    type: USB driver: uvcvideo
  Display: wayland server: X.Org v: 22.1.5 with: Xwayland v: 22.1.5
    compositor: Hyprland driver: X: loaded: amdgpu,nvidia dri: radeonsi
    gpu: amdgpu,nvidia,nvidia-nvswitch resolution: 1920x1080~144Hz
  API: OpenGL v: 4.6.0 NVIDIA 520.56.06 renderer: NVIDIA GeForce RTX 3060
    Laptop GPU/PCIe/SSE2
```
the monitor side of the configuration is the default:
```
monitor=,preferred,auto,1
```

```
298   │ [LOG] Applying monitor rule for HDMI-A-1
 299   │ [LOG] Setting preferred mode for HDMI-A-1
 300   │ [ERR] Couldn't commit output named HDMI-A-1
 301   │ [LOG] Monitor HDMI-A-1 layers arranged: reserved: 0.000000 0.000000 0.000000 0.000000
 302   │ [LOG] Framebuffer created, status 36053
 303   │ [LOG] Framebuffer created, status 36053
 304   │ [LOG] Framebuffer created, status 36053
 305   │ [LOG] Framebuffer created, status 36053
 306   │ [LOG] Allocated texture for BGTex
 307   │ [LOG] Background created for monitor eDP-1
 308   │ [LOG] Shaders initialized successfully.
 309   │ [LOG] Registered signal for owner d0edbe20: d1f445f0 -> d0edbf70 (owner: layerSurface)
 310   │ [LOG] Registered signal for owner d0edbe20: d1f3a658 -> d0edbe38 (owner: layerSurface)
 311   │ [LOG] Registered signal for owner d0edbe20: d1f3a668 -> d0edbea0 (owner: layerSurface)
 312   │ [LOG] Registered signal for owner d0edbe20: d1f3a678 -> d0edbf08 (owner: layerSurface)
 313   │ [LOG] Registered signal for owner d0edbe20: d1f3a688 -> d0edbfd8 (owner: layerSurface)
 314   │ [LOG] LayerSurface d1f3a580 (namespace wallpaper layer 0) created on monitor eDP-1
 315   │ [LOG] LayerSurface d1e1bc00 arranged: x: 0 y: 0 w: 1920 h: 1080 with margins: t: 0 l: 0 r: 0 b: 0
 316   │ [LOG] Monitor eDP-1 layers arranged: reserved: 0.000000 0.000000 0.000000 0.000000
 317   │ [LOG] New XWayland Surface created (class (null)).
 318   │ [LOG] Registered signal for owner d1f46690: d1f47fb8 -> d1f466f8 (owner: XWayland Window)
 319   │ [LOG] Registered signal for owner d1f46690: d1f47fc8 -> d1f46760 (owner: XWayland Window)
 320   │ [LOG] Registered signal for owner d1f46690: d1f47f38 -> d1f467c8 (owner: XWayland Window)
 321   │ [LOG] Registered signal for owner d0edc8f0: d1f54910 -> d0edca40 (owner: layerSurface)
 322   │ [LOG] Registered signal for owner d0edc8f0: d1f54b18 -> d0edc908 (owner: layerSurface)
 323   │ [LOG] Registered signal for owner d0edc8f0: d1f54b28 -> d0edc970 (owner: layerSurface)
 324   │ [LOG] Registered signal for owner d0edc8f0: d1f54b38 -> d0edc9d8 (owner: layerSurface)
 325   │ [LOG] Registered signal for owner d0edc8f0: d1f54b48 -> d0edcaa8 (owner: layerSurface)
 326   │ [LOG] LayerSurface d1f54a40 (namespace waybar layer 2) created on monitor eDP-1
 327   │ [LOG] LayerSurface d1e1b610 arranged: x: 0 y: 0 w: 1920 h: 36 with margins: t: 0 l: 0 r: 0 b: 0
 328   │ [LOG] LayerSurface d1e1bc00 arranged: x: 0 y: 0 w: 1920 h: 1080 with margins: t: 0 l: 0 r: 0 b: 0
```
