### ISSUE TITLE
80% of the screen black when I apply 144hz to monitor

### ISSUE THREAD

**Issue by dnikoloski** [hyprwm/Hyprland#1454]
**Reproduction**

```
cat ~/.config/hypr/hyprland.conf
monitor = DP-1,1920x1080@144, 0x0, 1
monitor = HDMI-A-1, 1920x1080, 1920x0, 1
```

![signal-2023-01-30-145127](https://user-images.githubusercontent.com/119594993/215511306-c53b549c-e16c-42a7-b89d-a4ef9cfcfec1.jpeg)

```
inxi -b
Graphics:
  Device-1: NVIDIA TU116 [GeForce GTX 1660 SUPER] driver: nouveau v: kernel
  Display: wayland server: X.org v: 1.21.1.6 with: Xwayland v: 22.1.7
    compositor: Hyprland driver: X: loaded: modesetting,nouveau dri: nouveau
    gpu: nouveau resolution: 1: 1920x1080~144Hz 2: 1920x1080~60Hz
  API: EGL/GBM Message: No known Wayland EGL/GBM data sources.
```
