### ISSUE TITLE
Keyboard losing focus, after using a floating popup (IntelliJ / Java?)

### ISSUE THREAD

**Issue by psobiech** [hyprwm/Hyprland#1947]
Hi,
when using a floating popup in IntelliJ (like 'Generate' popup), I am losing keyboard focus completely when the popup closes. I need to focus some other window (or change workspace) and refocus the original window to be able to type again. Mouse clicks within the application do not help. 

PS: The issue does not happen if I use mouse to close the popup, only if I'm using keyboard.

I've tried changing the follow_mouse option, but the behavior is the same. 
I will not post the config, since I was able to reproduce the issue even without the config (with the yellow banner on top ;-))

It might be easier to show on a video: https://youtu.be/HVOS8_YDTDo (I am clicking the mouse and typing after the popup closes multiple times), but no keyboard input goes through.

Thank you for your time!

Versions:
hyprland-git r2689.6519c030-1
wlroots-git 0.17.0.r6182.835208db-1

openjdk 19.0.2
IntelliJ IDEA 2023.1 (Same behaviour on the New UI and Old UI)

hyprctl clients:
```
Window 7b93aa0 -> root – TestClass.java [shared.simple-shared]:
        mapped: 1
        hidden: 0
        at: 961,5
        size: 954,1044
        workspace: 1 (1)
        floating: 0
        monitor: 0
        class: jetbrains-idea
        title: root – TestClass.java [shared.simple-shared]
        initialClass: jetbrains-idea
        initialTitle:
        pid: 629620
        xwayland: 1
        pinned: 0
        fullscreen: 0
        fullscreenmode: 0
        fakefullscreen: 0
        grouped: 0
        swallowing: 0

Window 7e9d7a0 -> Select Fields to Generate Getters:
        mapped: 1
        hidden: 0
        at: 1196,160
        size: 387,584
        workspace: 1 (1)
        floating: 1
        monitor: 0
        class: jetbrains-idea
        title: Select Fields to Generate Getters
        initialClass: jetbrains-idea
        initialTitle: Select Fields to Generate Getters
        pid: 629620
        xwayland: 1
        pinned: 0
        fullscreen: 0
        fullscreenmode: 0
        fakefullscreen: 0
        grouped: 0
        swallowing: 0
```

Here are the logs:
```
[LOG] Searching for matching rules for org.wezfurlong.wezterm (title: sobiechp@rip /tmp/hypr/6519c0308c4dd6ab484c7854e1eca2dc8f400485_1680638702 % tail -n 0 -f hyprland.log)
[LOG] Window 7b9e930 set title to sobiechp@rip /tmp/hypr/6519c0308c4dd6ab484c7854e1eca2dc8f400485_1680638702 % tail -n 0 -f hyprland.log
[LOG] Set keyboard focus to surface 7d71ff0, with window name: root – TestClass.java [shared.simple-shared]
[LOG] Searching for matching rules for jetbrains-idea (title: root – TestClass.java [shared.simple-shared])
[LOG] Window 7b93aa0 set title to root – TestClass.java [shared.simple-shared]
[LOG] Searching for matching rules for jetbrains-idea (title: root – TestClass.java [shared.simple-shared])
[LOG] Window 7b93aa0 set title to root – TestClass.java [shared.simple-shared]
[LOG] New XWayland Surface created (class jetbrains-idea).
[LOG] Window parent data: jetbrains-idea at 7e62b00
[LOG] Registered signal for owner 7e321c0: 7e8b7a8 -> 7e32228 (owner: XWayland Window)
[LOG] Registered signal for owner 7e321c0: 7e8b728 -> 7e322f8 (owner: XWayland Window)
[LOG] Registered signal for owner 7e321c0: 7e8b868 -> 7e328a8 (owner: XWayland Window)
[LOG] Registered signal for owner 7e321c0: 7e8b738 -> 7e32708 (owner: XWayland Window)
[LOG] Registered signal for owner 7e32910: 7e94a08 -> 7e32918 (owner: CWLSurface)
[LOG] CWLSurface 7e32910 called init()
[LOG] Registered signal for owner 7e321c0: 7e8b7b8 -> 7e32290 (owner: CWindow)
[LOG] Searching for matching rules for jetbrains-idea (title: win4)
[LOG] Window got assigned a surfaceTreeNode 0
[LOG] Registered signal for owner 7e321c0: 7e8b788 -> 7e32430 (owner: XWayland Window Late)
[LOG] Registered signal for owner 7e321c0: 7e8b798 -> 7e326a0 (owner: XWayland Window Late)
[LOG] Registered signal for owner 7e321c0: 7e8b7c8 -> 7e32360 (owner: XWayland Window Late)
[LOG] Registered signal for owner 7e321c0: 7e8b768 -> 7e32568 (owner: Xwayland Window Late)
[ERR] Tried to connect a listener twice?!
[LOG] Registered signal for owner 7e321c0: 7e8b878 -> 7e323c8 (owner: XWayland Window Late)
[LOG] Registered signal for owner 7e8a400: 7e949f8 -> 7e8a478 (owner: SurfaceTreeNode)
[LOG] Registered signal for owner 7e8a400: 7e949e8 -> 7e8a4e0 (owner: SurfaceTreeNode)
[LOG] Registered signal for owner 7e8a400: 7e94a08 -> 7e8a548 (owner: SurfaceTreeNode)
[LOG] Creating a surfaceTree Root! (pWindow: 7e321c0)
[LOG] Map request dispatched, monitor HDMI-A-1, xywh: 1082.000000 512.000000 233.000000 241.000000
[LOG] Window 7e321c0 unmapped (class jetbrains-idea)
[LOG] Unregistered late callbacks XWL
[LOG] Callback 7e32458 -> 7e32450, XWayland Window Late removed.
[LOG] Callback 7e326c8 -> 7e326c0, XWayland Window Late removed.
[LOG] Callback 7e32388 -> 7e32380, XWayland Window Late removed.
[LOG] Callback 7e323f0 -> 7e323e8, XWayland Window Late removed.
[LOG] Callback 7e32590 -> 7e32588, Xwayland Window Late removed.
[LOG] Framebuffer created, status 36053
[LOG] Unmapped was not focused, ignoring a refocus.
[LOG] Destroying the SubSurface tree of unmapped window 7e321c0
[LOG] Callback 7e8a508 -> 7e8a500, SurfaceTreeNode removed.
[LOG] Callback 7e8a570 -> 7e8a568, SurfaceTreeNode removed.
[LOG] Callback 7e8a4a0 -> 7e8a498, SurfaceTreeNode removed.
[LOG] SurfaceTree Node removed
[LOG] Callback 7e32940 -> 7e32938, CWLSurface removed.
[LOG] CWLSurface 7e32910 called destroy()
[LOG] Callback 7e322b8 -> 7e322b0, CWindow removed.
[LOG] Window 7e321c0 destroyed, queueing. (class )
[LOG] XWayland class raw: jetbrains-idea
[LOG] Callback 7e32250 -> 7e32248, XWayland Window removed.
[LOG] Callback 7e32320 -> 7e32318, XWayland Window removed.
[LOG] Callback 7e32730 -> 7e32728, XWayland Window removed.
[LOG] Callback 7e328d0 -> 7e328c8, XWayland Window removed.
[LOG] New XWayland Surface created (class jetbrains-idea).
[LOG] Window parent data: jetbrains-idea at 7e62b00
[LOG] Registered signal for owner 7e95100: 7e8b7a8 -> 7e95168 (owner: XWayland Window)
[LOG] Registered signal for owner 7e95100: 7e8b728 -> 7e95238 (owner: XWayland Window)
[LOG] Registered signal for owner 7e95100: 7e8b868 -> 7e957e8 (owner: XWayland Window)
[LOG] Registered signal for owner 7e95100: 7e8b738 -> 7e95648 (owner: XWayland Window)
[LOG] Registered signal for owner 7e95100: 7db6b60 -> 7e95718 (owner: Toplevel)
[LOG] Registered signal for owner 7e95100: 7db6b70 -> 7e95780 (owner: Toplevel)
[LOG] Registered signal for owner 7e95100: 7db6b80 -> 7e956b0 (owner: Toplevel)
[LOG] Registered signal for owner 7e95850: 7e94a08 -> 7e95858 (owner: CWLSurface)
[LOG] CWLSurface 7e95850 called init()
[LOG] Registered signal for owner 7e95100: 7e8b7b8 -> 7e951d0 (owner: CWindow)
[LOG] Searching for matching rules for jetbrains-idea (title: Select Fields to Generate Getters)
[LOG] Window got assigned a surfaceTreeNode 0
[LOG] Registered signal for owner 7e95100: 7e8b788 -> 7e95370 (owner: XWayland Window Late)
[LOG] Registered signal for owner 7e95100: 7e8b798 -> 7e955e0 (owner: XWayland Window Late)
[LOG] Registered signal for owner 7e95100: 7e8b7c8 -> 7e952a0 (owner: XWayland Window Late)
[LOG] Registered signal for owner 7e95100: 7e8b768 -> 7e954a8 (owner: Xwayland Window Late)
[ERR] Tried to connect a listener twice?!
[LOG] Registered signal for owner 7e623e0: 7e949f8 -> 7e62458 (owner: SurfaceTreeNode)
[LOG] Registered signal for owner 7e623e0: 7e949e8 -> 7e624c0 (owner: SurfaceTreeNode)
[LOG] Registered signal for owner 7e623e0: 7e94a08 -> 7e62528 (owner: SurfaceTreeNode)
[LOG] Creating a surfaceTree Root! (pWindow: 7e95100)
[LOG] Map request dispatched, monitor HDMI-A-1, xywh: 766.000000 248.000000 387.000000 584.000000
[LOG] Cleanup: destroyed a window
[LOG] Window 7e95100 unmapped (class jetbrains-idea)
[LOG] Unregistered late callbacks XWL
[LOG] Callback 7e95398 -> 7e95390, XWayland Window Late removed.
[LOG] Callback 7e95608 -> 7e95600, XWayland Window Late removed.
[LOG] Callback 7e952c8 -> 7e952c0, XWayland Window Late removed.
[LOG] Callback 7e954d0 -> 7e954c8, Xwayland Window Late removed.
[LOG] Framebuffer created, status 36053
[LOG] Unmapped was not focused, ignoring a refocus.
[LOG] Destroying the SubSurface tree of unmapped window 7e95100
[LOG] Callback 7e624e8 -> 7e624e0, SurfaceTreeNode removed.
[LOG] Callback 7e62550 -> 7e62548, SurfaceTreeNode removed.
[LOG] Callback 7e62480 -> 7e62478, SurfaceTreeNode removed.
[LOG] SurfaceTree Node removed
[LOG] Callback 7e95740 -> 7e95738, Toplevel removed.
[LOG] Callback 7e956d8 -> 7e956d0, Toplevel removed.
[LOG] Callback 7e957a8 -> 7e957a0, Toplevel removed.
[LOG] Callback 7e95880 -> 7e95878, CWLSurface removed.
[LOG] CWLSurface 7e95850 called destroy()
[LOG] Callback 7e951f8 -> 7e951f0, CWindow removed.
[LOG] Window 7e95100 destroyed, queueing. (class )
[LOG] XWayland class raw: jetbrains-idea
[LOG] Callback 7e95190 -> 7e95188, XWayland Window removed.
[LOG] Callback 7e95260 -> 7e95258, XWayland Window removed.
[LOG] Callback 7e95670 -> 7e95668, XWayland Window removed.
[LOG] Callback 7e95810 -> 7e95808, XWayland Window removed.
[LOG] Searching for matching rules for jetbrains-idea (title: root – TestClass.java [shared.simple-shared])
[LOG] Window 7b93aa0 set title to root – TestClass.java [shared.simple-shared]
[LOG] Searching for matching rules for jetbrains-idea (title: root – TestClass.java [shared.simple-shared])
[LOG] Window 7b93aa0 set title to root – TestClass.java [shared.simple-shared]
[LOG] Cleanup: destroyed a window
[LOG] Keybind triggered, calling dispatcher (8, , 65362)
```
