### ISSUE TITLE
Triple buffering to eliminate tearing?

### ISSUE THREAD

**Issue by GrabbenD** [hyprwm/Hyprland#2924]
# Overview

The ability to toggle triple buffering would introduce higher latency at the cost of smoother frames. This can be especially useful for singleplayer games or movies/series.

# Issue

I'm personally experiencing a lot of ~~tearing(?)~~ https://github.com/hyprwm/Hyprland/issues/2924#issuecomment-1684921490 even though vsync is disabled in game while Variable Refresh Rate is enabled in Hyprland while playing XWayland/Wine games. I found this combination of settings to be the smoothest:
```ini
misc:vrr = 1
misc:vfr = 0
misc:no_direct_scanout = 1
```

Here's a example of how the textures looks for me (apart from the massive horizontal line):
![tearing](https://github.com/hyprwm/Hyprland/assets/45666572/ae1a75f3-ee94-49fc-8fc8-ff577ca9a4a5)

**Similar issue can be observed in X11/DWM but it can be completely eliminated by activating Variable Refresh Rate + Tripe Buffering:**
```ini
# /etc/X11/xorg.conf.d/20-amdgpu.conf
Section "OutputClass"
    Identifier "AMD"
    MatchDriver "amdgpu"
    Driver "amdgpu"
    Option "VariableRefresh" "true"
    Option "TearFree" "true"
EndSection
```

**Comment by vaxerski** [comment]
I think that's something XWayland is doing, as Hyprland currently _cannot_ tear.

**Comment by Zeioth** [comment]
@GrabbenD I suggest you enabling [MangoHud](https://github.com/flightlessmango/MangoHud) to have more control over that:

```toml
### VSYNC [0-3] 0 = adaptive FreeSync; 1 = off; 2 = mailbox; 3 = FIFO
vsync=1

### OpenGL VSYNC [0-N] 0 = off; >=1 = wait for N v-blanks, N > 1 acts as a fps limiter (fps = display refresh rate / N)
gl_vsync=0
fps_limit=60
```

In this example config we are setting VRR and capping it to 60 fps (the monitor refresh rate) for reduced latency in gaming.

You can also spawn a TTY and run gamescope. This bypasses the compositor entirely, ensuring maximum performance on gaming.
