### ISSUE TITLE
External monitor doesn't work at first Hyprland launch with login manager (greetd)

### ISSUE THREAD

**Issue by Vaider7** [hyprwm/Hyprland#3515]
### Hyprland Version

Hyprland, built from branch main at commit 3d1a1679604e9de18a46a9a0819daf2044b08fa6 dirty (wsrules: check for workspace ID matches on numbered workspaces). Tag: v0.30.0-59-g3d1a1679

### Bug or Regression?

Bug

### Description

I use greetd as login manager with auto login option. After boot, Hyprland starts fine, but the external monitor doesn't work. When I close session and start Hyprland again, everything is all right. Also I found one workaround: in my ```stat_hypr``` script before invoking ```Hyprland``` I use ```sleep 2.5```, which make things fine.

My ```start_hypr``` script:
```nu
 #!/usr/bin/nu
sleep 2.5sec
let temp = (cd /tmp | mktemp XXXXXX-hyprland-log)
Hyprland o+e> $"/tmp/($temp)"
```

### How to reproduce

Use greetd with similar config
```toml
[terminal]
vt = 1

[default_session]
command = "agreety --cmd /home/user/.local/bin/start_hypr"
user = "user"

[initial_session]
command = "/home/user/.local/bin/start_hypr"
user = "user"
```
