### ISSUE TITLE
Monitor-workspace assignment not loading correctly?

### ISSUE THREAD

**Issue by muffinjets** [hyprwm/Hyprland#5464]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
[muffinjets@archlinux ~]$ hyprctl systeminfo
Hyprland, built from branch v0.38.1-b at commit 360ede79d124ffdeebbe8401f1ac4bc0dbec2c91  (props: bump ver to 0.38.1).
Date: Sat Apr 6 14:24:13 2024
Tag: v0.38.1

flags: (if any)


System Information:
System name: Linux
Node name: archlinux
Release: 6.8.2-arch2-1
Version: #1 SMP PREEMPT_DYNAMIC Thu, 28 Mar 2024 17:06:35 +0000


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GP107 [GeForce GTX 1050 Ti] [10de:1c82] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

[muffinjets@archlinux ~]$ 
```

</details>

### Bug or Regression?

Bug

### Description

I have two monitors.  Ideally, I'd like to set my primary monitor to have only workspace 1 on it, and my secondary monitor to be the one that swaps workspaces.  

To force this into happening, I have this outlined in my `hyprland.conf`:

```toml
# WORKSPACE CONFIG
# workspace=WORKSPACE,RULES
workspace=1,monitor:DP-1 default:true persistent:true
workspace=2,monitor:HDMI-A-1 default:true
workspace=3,monitor:HDMI-A-1 default:true
workspace=4,monitor:HDMI-A-1 default:true

# AUTOSTART
exec-once = hyprpaper & dunst & waybar
exec-once = [workspace 2 silent] flatpak run dev.vencord.Vesktop --disable-gpu
exec-once = [workspace 1] firefox
```

(And before it's said, `hyprctl monitors` reports the monitors with those identifications)

This not only does not lock workspaces 2-4 to HDMI-A-1, but when starting Hyprland from the display manager my firefox window starts in workplace 6 (for some reason??) on DP-1 and workspace 1 autostarted to HDMI-A-1.  

For shits and grins, I tried booting with all of the workspace rules commented out, just to have `hyprctl monitors` report that now my monitor identifications have changed to DP-2 and HDMI-A-3.

### How to reproduce

Unsure of how it can be replicated on another machine, but here's my steps:

With the [hyprland.txt](https://github.com/hyprwm/Hyprland/files/14895043/hyprland.txt) that I've included: (change filetype to `.conf` because GitHub didn't like me uploading that kind of file)

 - Have a DP and HDMI monitor?
 - Restart Hyprland/reboot to find workspace 6 open for some reason and your DP monitor not have workspace 1 on it
 - Comment/remove all of the lines in the "WORKSPACE CONFIG" section
 - Reboot to find that monitor assignment has changed
 - Replace WORKSPACE CONFIG to adjust to new layout
 - Reboot/reload to find yourself back to step 2

**Comment by muffinjets** [comment]
To add onto this, adding more defined workspaces with workspace rules alters the number that the actual first workspace generates on in an `n+2` pattern.

In the included config file, I have 4 workspaces defined with rules, and the system starts on 6.  
If I were to have 12 workspaces defined, it would put workspace 14 on DP-X.

**Comment by MightyPlaza** [comment]
use monitor description instead of port if they keep changing
if a program forks itself when starting workspace exec rules won't work

**Comment by muffinjets** [comment]
That's a lack of knowledge on my part, but the problem where workspace 1 isn't defined to the correct monitor persists, no matter what the monitor is named

**Comment by MightyPlaza** [comment]
you can also only have 1 default workspace per monitor
your syntax is also missing `,` between each rule

**Comment by muffinjets** [comment]
That's fine, but even after correcting that and having the monitors now being assigned by the description instead of the port, the issue persists.  Now workspace 1 is getting assigned to the HDMI monitor.  I can verify that the workspace isn't coincidentally showing up there via usage, it's reliably getting asssigned to the wrong monitor.  Will reply to this with new conf to confirm.

**Comment by muffinjets** [comment]
```toml

# MONITOR CONFIG
# monitor=name, resolution, position, scale
monitor=desc:ASUSTek COMPUTER INC ASUS VP278 J9LMTF140754,     1920x1080, 0x0,  1
monitor=desc:Sanyo Electric Co.Ltd. LCD TV, 1920x1080, 1920x0, 1

# WORKSPACE CONFIG
# workspace=WORKSPACE,RULES
workspace=1,monitor:ASUSTek COMPUTER INC ASUS VP278 J9LMTF140754, default:true, persistent:true
workspace=2,monitor:Sanyo Electric Co.Ltd. LCD TV,default:true
```

```sh
[muffinjets@archlinux ~]$ hyprctl monitors
Monitor HDMI-A-1 (ID 0):
	1920x1080@60.00000 at 1920x0
	description: Sanyo Electric Co.Ltd. LCD TV
<lines skipped for brevity>
Monitor DP-1 (ID 1):
	1920x1080@60.00000 at 0x0
	description: ASUSTek COMPUTER INC ASUS VP278 J9LMTF140754
```

**Comment by muffinjets** [comment]
My current (uneducated) is that my HDMI monitor is being initialized first, so there's nowhere else for workspace 1 to go.

**Comment by muffinjets** [comment]
You confident about that one?  When I adjust my conf to account for that, the HDMI monitor (Sanyo) is now loading the incorrect resolution/position as if it's not seeing the config line at all.

```toml
# MONITOR CONFIG
# monitor=name, resolution, position, scale
monitor=monitor:desc:ASUSTek COMPUTER INC ASUS VP278 J9LMTF140754, 1920x1080, 0x0,  1
monitor=monitor:desc:Sanyo Electric Co.Ltd. LCD TV, 1920x1080, 1920x0, 1
```

**Comment by muffinjets** [comment]
Where?  In the workspace rules or the monitor configuration?

**Comment by MightyPlaza** [comment]
workspace rule

**Comment by muffinjets** [comment]
Are you confident in that?  Because when I adjust my conf to account for that, I still get the same issue.

With this configuration:
```toml

# MONITOR CONFIG
# monitor=name, resolution, position, scale
monitor=desc:ASUSTek COMPUTER INC ASUS VP278 J9LMTF140754, 1920x1080, 0x0,  1
monitor=desc:Sanyo Electric Co.Ltd. LCD TV, 1920x1080, 1920x0, 1

# WORKSPACE CONFIG
# workspace=WORKSPACE,RULES
# workspace=1,monitor:DP-1, default=true
workspace=2,monitor:desc:Sanyo Electric Co.Ltd. LCD TV

# AUTOSTART
exec-once = hyprpaper & dunst & waybar
exec-once = [workspace 2 silent] flatpak run dev.vencord.Vesktop --disable-gpu
exec-once = [workspace 1] firefox
```

Workspace 1 is still being defaulted onto the wrong monitor.
