### ISSUE TITLE
per-monitor workspace specification is broken

### ISSUE THREAD

**Issue by alexlnkp** [hyprwm/Hyprland#5979]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Bug or Regression?

Bug

### Description

With the latest release, an error started to occur:
Trying to switch to workspace 2 (specifically 2 for some reason, other work fine) leads to no visible result, aside from hyprland unfocusing the tiles on the open workspace. Running `hyprctl workspaces` outputs the following:
```
workspace ID 2 (2) on monitor Unknown-1:
        monitorID: 1
        windows: 0
        hasfullscreen: 0
        lastwindow: 0x0
        lastwindowtitle: 

workspace ID 3 (3) on monitor DP-2:
        monitorID: 0
        windows: 1
        hasfullscreen: 0
        lastwindow: 0x64df36ce1690
        lastwindowtitle: Workspace Rules – Hyprland Wiki — LibreWolf

workspace ID 1 (1) on monitor DP-2:
        monitorID: 0
        windows: 1
        hasfullscreen: 0
        lastwindow: 0x64df36ca0d30
        lastwindowtitle: hyprland.conf - hypr - VSCodium
```
Which is rather odd, considering i have only a single monitor connected and there are no other monitors in the config file.
My config:
```
monitor=DP-2,1920x1080@165,0x0,1

# . . .

$mainMod = Alt

# . . .

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10
```
Note: i tried switching binds, didn't yield any results.

So, summary: trying to switch to workspace 2 leads to hyprland thinking the workspace 2 is located on a specific, unspecified monitor, therefore it focuses on it.

### How to reproduce

Pretty sure you can just attempt to switch to workspace 2

### Crash reports, logs, images, videos

> Logs can be found in /tmp/hypr

Well, not really. It was changed to `/run/user/1000/hypr/` with the latest release.

I am literally unable to attach the .log file by drag n dropping or using a clip here, i'll just upload it to a gist.
https://gist.github.com/alexlnkp/2ec1bf445d349ce262684944795114f6
