### ISSUE TITLE
Blurring waybar makes it's corners blurred too

### ISSUE THREAD

**Issue by cMerd** [hyprwm/Hyprland#6347]
### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
Date: Sat May 4 15:42:32 2024
Tag: v0.40.0, commits: 4606

flags: (if any)


System Information:
System name: Linux
Node name: merdiumarch
Release: 6.9.3-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 31 May 2024 15:14:45 +0000


GPU information: 
0000:00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 01) (prog-if 00 [VGA controller])
        DeviceName: VGA
0000:01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA107M [GeForce RTX 3050 Ti Mobile] [10de:25a0] (rev a1) (prog-if 00 [VGA controller])
        DeviceName: Second VGA


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:



```

</details>

### Bug or Regression?

Bug

### Description

**I'm unsure if this is a hyprland issue, or a waybar issue.**

I have waybar configuration, that uses transparent background and `rounded corners`. Here's the part that set it.
```css
* {
  font-family: BitstromWera Nerd Font;
  font-size: 15px;
  opacity: 0.95;
}

window#waybar {
  background-color: rgba(33, 33, 54, 0.65);
  color: #ffffff;
  border-width: 2px;
  border-color: #212155;
  border-style: solid;
  border-radius: 10px;
  opacity: 0.90;
}
```

I also have enabled `blur` in my **hyprland config**:
```config
decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

   rounding = 10

    blur {
        enabled = true
        size = 4
        passes = 5
        new_optimizations = true
        ignore_opacity = on
        xray = false
        brightness = 0.9
    } 
  
    drop_shadow = no
    shadow_range = 10
    shadow_render_power = 5
    col.shadow = rgba(4287f5aa)
}
```

And enabled **blur layer for waybar**:
```config
layerrule=blur, waybar
```

This however creates a bug, Hyprland blurs corners too:

### How to reproduce

Write something similar to this in /etc/xdg/waybar/style.css:
```css
window#waybar {
  background-color: rgba(33, 33, 54, 0.65);
  color: #ffffff;
  border-width: 2px;
  border-color: #212155;
  border-style: solid;
  border-radius: 10px
}
```

And enable blur for waybar in ~/.config/hypr/hyprland.conf:
```config
layerrule=blur, waybar
```

### Crash reports, logs, images, videos

![20240606-164228](https://github.com/hyprwm/Hyprland/assets/158254121/3fc59fe5-5aea-4769-a4db-77638a791a4b)
![20240606-164303](https://github.com/hyprwm/Hyprland/assets/158254121/b478d1b1-1764-416b-8aa7-682644f84ae4)
