### ISSUE TITLE
empty line between apps after upgrading to v0.47

### ISSUE THREAD

**Issue by sand4rt** [hyprwm/Hyprland#9205]
### Already reported ? *

- [x] I have searched the existing open and closed issues.

### Regression?

Definitely a regression - something broke after update (requires bisect)

### System Info and Hyprland Version

<details> <summary>System/Version info</summary>

```
Hyprland 0.47.0 built from branch  at commit 04ac46c54357278fc68f0a95d26347ea0db99496  (version: bump to 0.47.0).
Date: Mon Jan 27 11:43:43 2025
Tag: v0.47.0, commits: 5742
built against:
 aquamarine 0.7.1
 hyprlang 0.6.0
 hyprutils 0.5.0
 hyprcursor 0.1.11
 hyprgraphics 0.1.1


no flags were set


System Information:
System name: Linux
Node name: me
Release: 6.12.10-400.asahi.fc41.aarch64+16k
Version: #1 SMP PREEMPT_DYNAMIC Sat Jan 18 23:58:31 UTC 2025


GPU information: 
apple,agx-t8112
```

</details>

### Description

There is a strange empty line between my apps and waybar

### How to reproduce

1. open an app in a workspace without gaps
2. move the mouse or click on something

### Attach not paste

- [x] I understand that all text files must be *attached*, and not pasted directly. If not respected, this issue will likely get closed as spam

### Checklist of files to include below

- [x] Hyprland config - `hyprctl systeminfo -c` (always include)
- [x] Crash report (always include in case of crash)
- [x] Video (always include in case of a visual bug)
- [x] Logs (might contain useful info such as errors)

### Additional info & File uploads

https://github.com/user-attachments/assets/de74515e-5a2c-4f4f-8339-d130b0a8e5ec

**Comment by vaxerski** [comment]
jesus christ I had to put my face up to the screen.

I've seen this happen in some places due to waybar's fault, does it go away if you set waybar's opacity to like 0.99?

**Comment by vaxerski** [comment]
can you bisect it?

**Comment by sand4rt** [comment]
Can i just start bisecting and `make all` my `~/Hyprland` without breaking my env? I did not installed it from source

**Comment by kryzar** [comment]
Same here.

It's hardly visible on the screenshot:

![Image](https://github.com/user-attachments/assets/2cfd7d64-09e7-4ed8-84eb-5de04875b422)

But on a photo, one can see that there is a line, whose color is that of the border.

![Image](https://github.com/user-attachments/assets/60f2fcdb-346c-443a-8650-75d0fcfed92c)

**Comment by vaxerski** [comment]
does it go away if you disable borders?

**Comment by sand4rt** [comment]
The issue persists with Waybar and Hyprland borders disabled. Any tips on how to bisect this? Can I start bisecting and run `make all` in `~/Hyprland`? I didn’t install Hyprland from source

**Comment by vaxerski** [comment]
yes, then just run `./build/Hyprland` in a tty.

**Comment by kryzar** [comment]
> does it go away if you disable borders?

No. But it changes. I still have the line, but it's black instead of whatever the border color was set up to be.

**Comment by sand4rt** [comment]
I'm unable to build Hyprland using `make all` on Fedora due to missing dependencies. I had to install several packages, but i got stuck on xcursor, which doesn't seem to exist in Fedora's repositories. Here's one of the errors i encountered:

```sh
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:645 (message):
  The following required packages were not found:

   - aquamarine>=0.4.5
   ....
```

@kryzar are you able to provide a [bisect](https://wiki.hyprland.org/Crashes-and-Bugs/#bisecting-an-issue) ?

**Comment by vaxerski** [comment]
yeah outdated repos, suboptimal for bisecting

**Comment by kryzar** [comment]
> [@kryzar](https://github.com/kryzar) are you able to provide a [bisect](https://wiki.hyprland.org/Crashes-and-Bugs/#bisecting-an-issue) ?

Honestly I just use the arch packaged versions. If really one wants me to do that, I could, but I don't have the time to focus on building, testing and bisecting...

**Comment by vaxerski** [comment]
can anyone at least provide a minimal waybar config to repro?

**Comment by kryzar** [comment]
For what it's worth, here's mine. Let me know if you need anything.

`config`:

```json
// doc:      https://github.com/alexays/waybar/wiki/configuration
// examples: https://github.com/alexays/waybar/wiki/examples

{
    //////////////////
    // bar settings //
    //////////////////

    "position": "bottom",
    "mode": "dock",
    "fixed-center": "true",

    ///////////////////////
    // modules selection //
    ///////////////////////

    "modules-left"  : [
	    "hyprland/workspaces",
	    "hyprland/scratchpad"
    ],

    "modules-center": [
	    "clock"
    ],

    "modules-right" : [
	    "battery",
        "tray",
    ],


    ///////////////////////////
    // modules configuration //
    ///////////////////////////

    "hyprland/workspaces": {
        "disable-scroll": true
    },

    "keyboard-state": {
        "numlock": true,
        "capslock": true,
        "format": "{name} {icon}",
        "format-icons": {
            "locked": "",
            "unlocked": ""
        }
    },

    "clock": {
        // https://github.com/alexays/waybar/wiki/module:-clock
        // "format": "{:%h:%m, %d %b}"
        "format": "{:l%d %b %h:%m}",
        "locale": "fr_fr.utf8",
    },

    "battery": {
	// https://github.com/alexays/waybar/wiki/module:-battery
	// icônes : nf-md-battery
	//     https://www.nerdfonts.com/cheat-sheet
        "states": {
            "good": 70,
            "warning": 20,
            "critical": 10
        },
	"interval": 1,
        "format":          "{capacity}-",
        "format-charging": "{capacity}+",
        "format-plugged":  "{capacity}?",
	// 󰂄󰚥
	// "format-icons": ["󰁹", "󰂂", "󰂁", "󰂀", "󰁿", "󰁾", "󰁽", "󰁼", "󰁻", "󰁺"],
	// "format-icons": ["󰁺", "󰁻", "󰁼", "󰁽", "󰁾", "󰁿", "󰂀", "󰂁", "󰂂", "󰁹"]

    },

    "network": {
	// https://github.com/alexays/waybar/wiki/module:-network
	"interval": 1,
	"format": "{bandwidthtotalbits}",
        "tooltip-format": "{essid}",
        "format-disconnected": "non connecté ! ⚠"
    },

    "tray": {
        "icon-size": 22,
        "spacing": 8
    }
}
```

`style.css`:

```css
/***********/
/* GENERAL */
/***********/

* {
    font-family: SF Mono;
    font-size: 12pt;
    color: white;
}

window {
    background-color: #191724;
    color: #e0def4;
    padding: 0;
    margin: 0;
    transition-property: background-color;
    transition-duration: .5s;
    border: 1px solid black;
}

/* MARGINS */

#network {
    margin-right: 0.2cm;
}


/*****************/
/* MODULES RIGHT */
/*****************/

.modules-right * {
    /* color: rgba(255, 255, 255, 0.6); */
    color: #6e6a86;
    margin-right: 0;
}


/**********************/
/* INDIVIDUAL MODULES */
/**********************/

/* WORKSPACES */

#workspaces {
  margin-right: 1cm;
}

#workspaces button {
    padding: 0;
    margin-right: 3px;
}

#workspaces button * {
    /* color: rgba(255, 255, 255, 0.6); */
    color: #6e6a86;
}

#workspaces button:hover * {
    color: #9ccfd8;
    font-weight: bold;
}

/* https://wiki.hyprland.org/Useful-Utilities/Status-Bars/#active-workspace-doesnt-show-up */

#workspaces button.active {
    /* border-bottom: 2px solid red; */
    border-radius: 0;
    font-weight: bold;
}

#workspaces button.active * {
    color: white;
}

button:hover {
    background: inherit;
}

button:hover * {
    color: red;
    font-weight: bold;
}

/* MODE */

#mode {
    background-color: #64727D;
    border-bottom: 3px solid #ffffff;
}


/* BATTERY */

#battery {
    padding-left: 0.1cm;
    padding-right: 0.1cm;
}

#battery.warning {
    font-weight: bold;
    color: orange;
}

#battery.critical {
    animation-name: blink;
    font-weight: bold;
    color: red;
}

label:focus {
    background-color: #000000;
}

/* TRAY */

#tray {
    margin-left: 0.3cm;
}

#tray menu {
    background: black;
}

#tray menu * {
    color: white;
}
```

**Comment by vaxerski** [comment]
I can't reproduce it. I see a black outline (which you have configured) and nothing amiss.

**Comment by sand4rt** [comment]
> can anyone at least provide a minimal waybar config to repro?

It happens with:

```
// waybar/config.jsonc
{
    "layer": "top",
    "height": 39, // NOTE: height": 40 does not cause the line
    "spacing": 0,
    "modules-left": [],
    "modules-center": [],
    "modules-right": [],
}
```

```css
window#waybar {
    background-color: #252526;
}
```

I just discovered that setting `"height": 40` doesn’t cause the empty line. Maybe some fractional scaling issue? My Hyprland config includes `monitor=,highres,auto,1.5` btw
