### ISSUE TITLE
Black screen when monitor set in hypland.conf (6.13.1-arch1-1)

### ISSUE THREAD

**Issue by Ernestas-t** [hyprwm/Hyprland#9339]
### Already reported ? *

- [x] I have searched the existing open and closed issues.

### Regression?

Definitely a regression - something broke after update (requires bisect)

### System Info and Hyprland Version

<details> <summary>System/Version info</summary>

```
<Hyprland 0.47.2 built from branch  at commit 882f7ad7d2bbfc7440d0ccaef93b1cdd78e8e3ff  (version: bump to 0.47.2).
Date: Sun Feb 2 00:47:17 2025
Tag: v0.47.2, commits: 5767
built against:
 aquamarine 0.7.2
 hyprlang 0.6.0
 hyprutils 0.5.0
 hyprcursor 0.1.11
 hyprgraphics 0.1.1


no flags were set


System Information:
System name: Linux
Node name: archlinux
Release: 6.13.1-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Sun, 02 Feb 2025 01:02:29 +0000


GPU information:
64:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Phoenix1 [1002:15bf] (rev dd) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
>
```

</details>

### Description

After latest upgrade of arch linux to 6.13.1-arch1-1 monitor configuration is broken and produces a black screen. This issue can not be replicated on LTS.

I'm using the integrated display on a Thinkpad p14s:
```

Monitor eDP-1 (ID 0):
        2880x1800@60.00100 at 0x0
        description: Lenovo Group Limited 0x4149
        make:
Monitor eDP-1 (ID 0):
        2880x1800@60.00100 at 0x0
        description: Lenovo Group Limited 0x4149
        make: Lenovo Group Limited
        model: 0x4149
        serial:
        active workspace: 1 (1)
        special workspace: 0 ()
        reserved: 0 37 0 0
        scale: 2.00
        transform: 0
        focused: yes
        dpmsStatus: 1
        vrr: false
        solitary: 0
        activelyTearing: false
        directScanoutTo: 0
        disabled: false
        currentFormat: XRGB8888
        mirrorOf: none
        availableModes: 2880x1800@60.00Hz 1920x1200@60.00Hz 1920x1080@60.00Hz 1600x1200@60.00Hz 1680x1050@60.00Hz 1280x1024@60.00Hz 1440x900@60.00Hz 1280x800@60.00Hz 1280x720@60.00Hz 1024x768@60.00Hz 800x600@60.00Hz 640x480@60.00Hz Lenovo Group Limited
        model: 0x4149
        serial:
        active workspace: 1 (1)
        special workspace: 0 ()
        reserved: 0 37 0 0
        scale: 2.00
        transform: 0
        focused: yes
        dpmsStatus: 1
        vrr: false
        solitary: 0
        activelyTearing: false
        directScanoutTo: 0
        disabled: false
        currentFormat: XRGB8888
        mirrorOf: none
        availableModes: 2880x1800@60.00Hz 1920x1200@60.00Hz 1920x1080@60.00Hz 1600x1200@60.00Hz 1680x1050@60.00Hz 1280x1024@60.00Hz 1440x900@60.00Hz 1280x800@60.00Hz 1280x720@60.00Hz 1024x768@60.00Hz 800x600@60.00Hz 640x480@60.00Hz
```

the faulty line is in the configuration file:

monitor = eDP-1, 2880x1800@90, 0x0, 1.5

removing this gives me output, but setting any monitor settings immediately produces a black screen.

Logs for reference:
```
[LOG] Old rlimit: soft -> 1024, hard -> 524288
[LOG] New rlimit: soft -> 524288, hard -> 524288
[LOG] Creating the EventLoopManager!
[LOG] Creating the HookSystem!
[LOG] Creating the KeybindManager!
[LOG] Creating the AnimationManager!
[LOG] Creating the ConfigManager!
[LOG] Using config: /home/ernestas/.config/hypr/hyprland.conf
[INFO] !!!!HEY YOU, YES YOU!!!!: further logs to stdout / logfile are disabled by default. BEFORE SENDING THIS LOG, ENABLE THEM. Use debug:disable_logs = false to do so: https://wiki.hyprland.org/Configuring/Variables/#debug
[LOG] Creating the CHyprError!
[LOG] Creating the LayoutManager!
[LOG] Creating the TokenManager!
[LOG] [hookSystem] New hook event registered: preConfigReload
[LOG] Using config: /home/ernestas/.config/hypr/hyprland.conf
[LOG] CWindowRule: direct prop rule found, rewritten nofocus -> prop nofocus
Environment variable $QT_QPA_PLATFORMTHEME not set, ignoring.
Environment variable $XDG_DATA_DIRS not set, ignoring.
[LOG] Registered timeout rule for 300s:
      on-timeout: hyprlock
      on-resume:
[LOG] Registered timeout rule for 900s:
      on-timeout: hyprctl dispatch dpms off
      on-resume: hyprctl dispatch dpms on
[LOG] Welcome to hyprpaper!
built from commit  ()
[LOG] Cleaned old hyprpaper preloads (3), removing 112.9MB
Environment variable $QT_QPA_PLATFORMTHEME not set, ignoring.
Environment variable $XDG_DATA_DIRS not set, ignoring.
[LOG]   | got iface: wl_seat v9
[LOG]    > Bound to wl_seat v9
[LOG]   | got iface: wl_data_device_manager v3
[LOG]   | got iface: wl_compositor v6
[LOG]   | got iface: wl_subcompositor v1
[LOG]   | got iface: wl_shm v1
[LOG]   | got iface: wp_viewporter v1
[LOG]   | got iface: wp_tearing_control_manager_v1 v1
[LOG]   | got iface: wp_fractional_scale_manager_v1 v1
[LOG]   | got iface: zxdg_output_manager_v1 v3
[LOG]   | got iface: wp_cursor_shape_manager_v1 v1
[LOG]   | got iface: zwp_idle_inhibit_manager_v1 v1
[LOG]   | got iface: zwp_relative_pointer_manager_v1 v1
[LOG]   | got iface: zxdg_decoration_manager_v1 v1
[LOG]   | got iface: wp_alpha_modifier_v1 v1
[LOG]   | got iface: zwlr_gamma_control_manager_v1 v1
[LOG]   | got iface: ext_foreign_toplevel_list_v1 v1
[LOG]   | got iface: zwp_pointer_gestures_v1 v3
[LOG]   | got iface: zwlr_foreign_toplevel_manager_v1 v3
[LOG]   | got iface: zwp_keyboard_shortcuts_inhibit_manager_v1 v1
[LOG]   | got iface: zwp_text_input_manager_v1 v1
[LOG]   | got iface: zwp_text_input_manager_v3 v1
[LOG]   | got iface: zwp_pointer_constraints_v1 v1
[LOG]   | got iface: zwlr_output_power_manager_v1 v1
[LOG]   | got iface: xdg_activation_v1 v1
[LOG]   | got iface: ext_idle_notifier_v1 v1
[LOG]    > Bound to ext_idle_notifier_v1 v1
[LOG]   | got iface: hyprland_lock_notifier_v1 v1
[LOG]   | got iface: ext_session_lock_manager_v1 v1
[LOG]   | got iface: zwp_input_method_manager_v2 v1
[LOG]   | got iface: zwp_virtual_keyboard_manager_v1 v1
[LOG]   | got iface: zwlr_virtual_pointer_manager_v1 v2
[LOG]   | got iface: zwlr_output_manager_v1 v4
[LOG]   | got iface: org_kde_kwin_server_decoration_manager v1
[LOG]   | got iface: hyprland_focus_grab_manager_v1 v1
[LOG]   | got iface: zwp_tablet_manager_v2 v1
[LOG]   | got iface: zwlr_layer_shell_v1 v5
[LOG]   | got iface: wp_presentation v1
[LOG]   | got iface: xdg_wm_base v6
[LOG]   | got iface: zwlr_data_control_manager_v1 v2
[LOG]   | got iface: zwp_primary_selection_device_manager_v1 v1
[LOG]   | got iface: xwayland_shell_v1 v1
[LOG]   | got iface: zwlr_screencopy_manager_v1 v3
[LOG]   | got iface: hyprland_toplevel_export_manager_v1 v2
[LOG]   | got iface: hyprland_global_shortcuts_manager_v1 v1
[LOG]   | got iface: xdg_dialog_v1 v1
[LOG]   | got iface: wp_single_pixel_buffer_manager_v1 v1
[LOG]   | got iface: wp_security_context_manager_v1 v1
[LOG]   | got iface: hyprland_ctm_control_manager_v1 v1
[LOG]   | got iface: hyprland_surface_manager_v1 v2
[LOG]   | got iface: wp_drm_lease_device_v1 v1
[LOG]   | got iface: wp_linux_drm_syncobj_manager_v1 v1
[LOG]   | got iface: wl_drm v2
[LOG]   | got iface: zwp_linux_dmabuf_v1 v5
[LOG]   | got iface: wl_output v4
[LOG] found 2 rules
[LOG] wayland done, registering dbus
[LOG] Using dbus path /org/freedesktop/login1/session/_31
[ERR] Couldn't connect to session dbus
err: [org.freedesktop.DBus.Error.FileExists] Failed to request bus name (File exists)
[2025-02-05 15:26:38.288] [info] Using configuration file /home/ernestas/.config/waybar/config
[2025-02-05 15:26:38.291] [info] Unable to receive desktop appearance: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop
[2025-02-05 15:26:38.291] [info] Using CSS file /home/ernestas/.config/waybar/style.css
[2025-02-05 15:26:38.302] [info] Hyprland IPC starting
[2025-02-05 15:26:38.304] [info] Loading persistent workspaces from Waybar config
[2025-02-05 15:26:38.304] [info] Loading persistent workspaces from Hyprland workspace rules
[LOG] Preloaded target /home/ernestas/.config/hypr/wallpapers/cactus.jpg in 119.58ms -> Pixel size: [4042, 2695]
[LOG] Buffer created for target /home/ernestas/.config/hypr/wallpapers/cactus.jpg, Shared Memory usage: 82.9MB
[LOG] Total SM usage for all buffers: 82.9MB
[LOG] hyprpaper socket started at /run/user/1000/hypr/882f7ad7d2bbfc7440d0ccaef93b1cdd78e8e3ff_1738761995_943416860/.hyprpaper.sock (fd: 6)
[LOG] configure for eDP-1
[LOG] configure for eDP-1
[LOG] Buffer created for target /home/ernestas/.config/hypr/wallpapers/cactus.jpg, Shared Memory usage: 9.2MB
[LOG] Total SM usage for all buffers: 92.2MB
[LOG] Image data for eDP-1: /home/ernestas/.config/hypr/wallpapers/cactus.jpg at [0.00, -84.38], scale: 0.48 (original image size: [4042, 2695])
[2025-02-05 15:26:38.486] [info] Bar configured (width: 1920, height: 37) for output: eDP-1
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 708, clipping.
>                   X11 cannot support keycodes above 255.
> Warning:          Could not resolve keysym XF86KbdInputAssistPrevgrou
> Warning:          Could not resolve keysym XF86KbdInputAssistNextgrou
Errors from xkbcomp are not fatal to the X server
[LOG] Submitting viewport dest size 1920x1200 for 61a28d36c2d0
[LOG] handlePreferredScale: 1.50 for 61a28d36c2d0
[LOG] Buffer created for target /home/ernestas/.config/hypr/wallpapers/cactus.jpg, Shared Memory usage: 20.7MB
[LOG] Total SM usage for all buffers: 112.9MB
[LOG] Image data for eDP-1: /home/ernestas/.config/hypr/wallpapers/cactus.jpg at [0.00, -84.38], scale: 0.71 (original image size: [4042, 2695])
[LOG] Submitting viewport dest size 1920x1200 for 61a28d36c2d0
```

### How to reproduce

1. update to the newest arch kernel (6.13.1-arch1-1)
2. configure monitor settings: monitor = eDP-1, 2880x1800@90, 0x0, 1.5

### Attach not paste

- [x] I understand that all text files must be *attached*, and not pasted directly. If not respected, this issue will likely get closed as spam

### Checklist of files to include below

- [x] Hyprland config - `hyprctl systeminfo -c` (always include)
- [x] Crash report (always include in case of crash)
- [x] Video (always include in case of a visual bug)
- [x] Logs (might contain useful info such as errors)
